'This form is the user interface for the study of the Julia Set
'generated by the iteration z -> z^2+c
'In addition, the Mandelbrot set can be generated as well

'The form is based on the Interface IJulia
'that is implemented by ClsJulia and ClsMandelbrot
'Therefore, more cases of polynoms could be easely programmed
'by implementing this interface

'Status Checked

Public Class FrmJulia

    'Private global variables
    Private IsFormLoaded As Boolean
    Private FC As ClsJuliaController

    Private ReadOnly LM As ClsLanguageManager

    'SECTOR INITIALIZATION
    Public Sub New()

        'This is necessary for the designer
        InitializeComponent()
        LM = ClsLanguageManager.LM
    End Sub

    Private Sub FrmJuliaSet_Load(sender As Object, e As EventArgs) Handles Me.Load

        'Generate objects
        IsFormLoaded = False
        FC = New ClsJuliaController(Me)

        'Initialize Language
        InitializeLanguage()
        FC.FillDynamicSystem()
    End Sub

    Private Sub FrmJuliaSet_Shown(sender As Object, e As EventArgs) Handles Me.Shown

        FC.SetDS()
        IsFormLoaded = True
    End Sub

    Private Sub InitializeLanguage()

        Text = LM.GetString("JuliaMandelbrot")
        BtnReset.Text = LM.GetString("ResetIteration")
        LblTime.Text = LM.GetString("Time")
        LblNumberOfSteps.Text = LM.GetString("Steps")
        LblProtocol.Text = LM.GetString("ProtocolJulia")
        ChkProtocol.Text = LM.GetString("Protocol")
        GrpColors.Text = LM.GetString("Colors")
        OptSystem.Text = LM.GetString("System")
        OptUser.Text = LM.GetString("UserDefined")
        BtnDefault.Text = LM.GetString("DefaultUserData")
        LblJuliaSets.Text = LM.GetString("Samples")

    End Sub

    Private Sub BtnDefault_Click(sender As Object, e As EventArgs) Handles BtnDefault.Click
        If IsFormLoaded Then
            FC.ResetIteration()
            FC.SetDefaultUserData()
        End If
    End Sub

    Private Sub BtnReset_Click(sender As Object, e As EventArgs) Handles BtnReset.Click
        If IsFormLoaded Then
            FC.ResetIteration()
        End If
    End Sub

    Private Sub CboFunction_SelectedIndexChanged(sender As Object, e As EventArgs) Handles CboFunction.SelectedIndexChanged
        If IsFormLoaded Then
            FC.SetDS()
        End If
    End Sub

    Private Sub CboN_SelectedIndexChanged(sender As Object, e As EventArgs) Handles CboN.SelectedIndexChanged
        If IsFormLoaded Then
            FC.SetExponent()
        End If
    End Sub

    Private Sub TxtXMax_TextChanged(sender As Object, e As EventArgs) Handles TxtXMax.TextChanged
        If IsFormLoaded Then
            FC.SetDelta()
        End If
    End Sub

    Private Sub TxtXMin_TextChanged(sender As Object, e As EventArgs) Handles TxtXMin.TextChanged
        If IsFormLoaded Then
            FC.SetDelta()
        End If
    End Sub

    Private Sub TxtYMax_TextChanged(sender As Object, e As EventArgs) Handles TxtYMax.TextChanged
        If IsFormLoaded Then
            FC.SetDelta()
        End If
    End Sub

    Private Sub TxtYMin_TextChanged(sender As Object, e As EventArgs) Handles TxtYMin.TextChanged
        If IsFormLoaded Then
            FC.SetDelta()
        End If
    End Sub

    Private Sub TrbBlue_Scroll(sender As Object, e As EventArgs) Handles TrbBlue.Scroll
        If IsFormLoaded Then
            FC.SetColors()
        End If
    End Sub

    Private Sub TrbGreen_Scroll(sender As Object, e As EventArgs) Handles TrbGreen.Scroll
        If IsFormLoaded Then
            FC.SetColors()
        End If
    End Sub

    Private Sub TrbRed_Scroll(sender As Object, e As EventArgs) Handles TrbRed.Scroll
        If IsFormLoaded Then
            FC.SetColors()
        End If
    End Sub

    Private Sub OptSystem_CheckedChanged(sender As Object, e As EventArgs) Handles OptSystem.CheckedChanged
        If IsFormLoaded Then
            If OptSystem.Checked Then
                FC.SetColors()
                FC.SetDefaultUserData()
                FC.ResetIteration()
            End If
        End If
    End Sub

    Private Sub OptUser_CheckedChanged(sender As Object, e As EventArgs) Handles OptUser.CheckedChanged
        If IsFormLoaded Then
            If OptUser.Checked Then
                FC.SetColors()
                FC.SetDefaultUserData()
                FC.ResetIteration()
            End If
        End If
    End Sub

    Private Sub CboSamples_SelectedIndexChanged(sender As Object, e As EventArgs) Handles CboJuliaSamples.SelectedIndexChanged
        If IsFormLoaded Then
            FC.SetSample()
        End If
    End Sub

    'SECTOR ITERATION

    Private Sub BtnStart_Click(sender As Object, e As EventArgs) Handles BtnStart.Click
        If IsFormLoaded Then
            FC.StartIteration()
        End If
    End Sub

    Private Sub BtnStop_Click(sender As Object, e As EventArgs) Handles BtnStop.Click
        If IsFormLoaded Then
            FC.StopIteration()
        End If
    End Sub

End Class