'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LabelsEN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Simulator.LabelsEN", GetType(LabelsEN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die About Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutSimulator() As String
            Get
                Return ResourceManager.GetString("AboutSimulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Action Stopped ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ActionStopped() As String
            Get
                Return ResourceManager.GetString("ActionStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alfa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Alfa() As String
            Get
                Return ResourceManager.GetString("Alfa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color of the next Ball ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallColor() As String
            Get
                Return ResourceManager.GetString("BallColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speed of all Balls ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallSpeed() As String
            Get
                Return ResourceManager.GetString("BallSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Billard() As String
            Get
                Return ResourceManager.GetString("Billard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billard Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BillardTable() As String
            Get
                Return ResourceManager.GetString("BillardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Black ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Black() As String
            Get
                Return ResourceManager.GetString("Black", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Blue() As String
            Get
                Return ResourceManager.GetString("Blue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die C-Diagram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property C_Diagram() As String
            Get
                Return ResourceManager.GetString("C-Diagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Colored Diagram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ColoredDiagram() As String
            Get
                Return ResourceManager.GetString("ColoredDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Coordinates of the Startpoint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoordinatesStartpoint() As String
            Get
                Return ResourceManager.GetString("CoordinatesStartpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Delta() As String
            Get
                Return ResourceManager.GetString("Delta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Difference x2 - x1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Difference12() As String
            Get
                Return ResourceManager.GetString("Difference12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die d in [0,10] = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DinStretching() As String
            Get
                Return ResourceManager.GetString("DinStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Draw Billard Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawBillardTable() As String
            Get
                Return ResourceManager.GetString("DrawBillardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Draw Function Graph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawFunctionGraph() As String
            Get
                Return ResourceManager.GetString("DrawFunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dr. math. ETHZ Hermann Biner, Zermatt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrMathETH() As String
            Get
                Return ResourceManager.GetString("DrMathETH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elliptic ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Elliptic() As String
            Get
                Return ResourceManager.GetString("Elliptic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elliptic Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EllipticBillard() As String
            Get
                Return ResourceManager.GetString("EllipticBillard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Examinated Parameter Range: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedParameterRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedParameterRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Examinated Value Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedValueParameter() As String
            Get
                Return ResourceManager.GetString("ExaminatedValueParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Examinated Value Range: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedValueRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedValueRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Experiment No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExperimentNo() As String
            Get
                Return ResourceManager.GetString("ExperimentNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Factor C ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FactorC() As String
            Get
                Return ResourceManager.GetString("FactorC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feedback is appreciated ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Feedback() As String
            Get
                Return ResourceManager.GetString("Feedback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feigenbaum Diagram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FeigenbaumDiagram() As String
            Get
                Return ResourceManager.GetString("FeigenbaumDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Function Graph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FunctionGraph() As String
            Get
                Return ResourceManager.GetString("FunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Green() As String
            Get
                Return ResourceManager.GetString("Green", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Histogram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Histogram() As String
            Get
                Return ResourceManager.GetString("Histogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hitpont Parameter t ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HitPoint() As String
            Get
                Return ResourceManager.GetString("HitPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A Dual Number can only contain the Digits 0 and 1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDualNumberDigits() As String
            Get
                Return ResourceManager.GetString("InvalidDualNumberDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid Parameter Value or Iteration Value! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidParameterOrIterationValue() As String
            Get
                Return ResourceManager.GetString("InvalidParameterOrIterationValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Protocol can only contain the Digits 0 and 1! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidProtocolDigits() As String
            Get
                Return ResourceManager.GetString("InvalidProtocolDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid User Ranges ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserRanges() As String
            Get
                Return ResourceManager.GetString("InvalidUserRanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Iteration() As String
            Get
                Return ResourceManager.GetString("Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration Depth ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IterationDepth() As String
            Get
                Return ResourceManager.GetString("IterationDepth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The left interval border must be smaller than the right interval border! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LeftSmallerRight() As String
            Get
                Return ResourceManager.GetString("LeftSmallerRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Log() As String
            Get
                Return ResourceManager.GetString("Log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logistic Growth ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogisticGrowth() As String
            Get
                Return ResourceManager.GetString("LogisticGrowth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Angle of lower Pendulum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LowerPendulumAngle() As String
            Get
                Return ResourceManager.GetString("LowerPendulumAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Magenta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Magenta() As String
            Get
                Return ResourceManager.GetString("Magenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please by Mail to h.biner@bluewin.ch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MailTo() As String
            Get
                Return ResourceManager.GetString("MailTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Handbuch.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Manual() As String
            Get
                Return ResourceManager.GetString("Manual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dokumentation Simulator.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MathDoc() As String
            Get
                Return ResourceManager.GetString("MathDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuBillard() As String
            Get
                Return ResourceManager.GetString("MnuBillard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;C-Diagram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuCDiagram() As String
            Get
                Return ResourceManager.GetString("MnuCDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuClose() As String
            Get
                Return ResourceManager.GetString("MnuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Documentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuDocumentation() As String
            Get
                Return ResourceManager.GetString("MnuDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuEnglish() As String
            Get
                Return ResourceManager.GetString("MnuEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Feigenbaum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFeigenbaum() As String
            Get
                Return ResourceManager.GetString("MnuFeigenbaum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFile() As String
            Get
                Return ResourceManager.GetString("MnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Fractals ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFractals() As String
            Get
                Return ResourceManager.GetString("MnuFractals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuGerman() As String
            Get
                Return ResourceManager.GetString("MnuGerman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Histogram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuHistogram() As String
            Get
                Return ResourceManager.GetString("MnuHistogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuInfo() As String
            Get
                Return ResourceManager.GetString("MnuInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuIteration() As String
            Get
                Return ResourceManager.GetString("MnuIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Julia Set ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuJuliaSet() As String
            Get
                Return ResourceManager.GetString("MnuJuliaSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Komplex Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuKomplexIteration() As String
            Get
                Return ResourceManager.GetString("MnuKomplexIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuLanguage() As String
            Get
                Return ResourceManager.GetString("MnuLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMain() As String
            Get
                Return ResourceManager.GetString("MnuMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mandelbrot Set ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMandelbrotSet() As String
            Get
                Return ResourceManager.GetString("MnuMandelbrotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Manual ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuManual() As String
            Get
                Return ResourceManager.GetString("MnuManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die M&amp;athematics ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMathematics() As String
            Get
                Return ResourceManager.GetString("MnuMathematics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mechanics ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMechanics() As String
            Get
                Return ResourceManager.GetString("MnuMechanics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Pendulum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuPendulum() As String
            Get
                Return ResourceManager.GetString("MnuPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Sensitivity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuSensitivity() As String
            Get
                Return ResourceManager.GetString("MnuSensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTest() As String
            Get
                Return ResourceManager.GetString("MnuTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Two Dimensions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTwoDimensions() As String
            Get
                Return ResourceManager.GetString("MnuTwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Unimodal Functions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuUnimodal() As String
            Get
                Return ResourceManager.GetString("MnuUnimodal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Ball ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NewBall() As String
            Get
                Return ResourceManager.GetString("NewBall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Next 100 Steps ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next100Steps() As String
            Get
                Return ResourceManager.GetString("Next100Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Next 10 Steps ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next10Steps() As String
            Get
                Return ResourceManager.GetString("Next10Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Next Diagram ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextDiagram() As String
            Get
                Return ResourceManager.GetString("NextDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Next Step ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextStep() As String
            Get
                Return ResourceManager.GetString("NextStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There are no Balls on the Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoBallsOnTable() As String
            Get
                Return ResourceManager.GetString("NoBallsOnTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No Intersection Point found ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoIntersectionPoint() As String
            Get
                Return ResourceManager.GetString("NoIntersectionPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die If the behaviour is not chaotic, the result will not be as expected! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NonChaoticBehaviour() As String
            Get
                Return ResourceManager.GetString("NonChaoticBehaviour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No Startpoint set! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoStartPointSet() As String
            Get
                Return ResourceManager.GetString("NoStartPointSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  is not allowed. It has to be in the Interval:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotAlllowedValue() As String
            Get
                Return ResourceManager.GetString("NotAlllowedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This function is not implemented yet ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotImplemented() As String
            Get
                Return ResourceManager.GetString("NotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Number of Steps ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfSteps() As String
            Get
                Return ResourceManager.GetString("NumberOfSteps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This must be a numeric value ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumericValue() As String
            Get
                Return ResourceManager.GetString("NumericValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die In this project, only numbers of type Integer and Decimal are allowed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OnlyDecAndInt() As String
            Get
                Return ResourceManager.GetString("OnlyDecAndInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Oval() As String
            Get
                Return ResourceManager.GetString("Oval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oval Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OvalBillard() As String
            Get
                Return ResourceManager.GetString("OvalBillard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parabola ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Parabola() As String
            Get
                Return ResourceManager.GetString("Parabola", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Parameter() As String
            Get
                Return ResourceManager.GetString("Parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This Parameter Range is not allowed! It must be part of the interval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParameterRangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("ParameterRangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phase Portrait t, alfa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PhasePortrait() As String
            Get
                Return ResourceManager.GetString("PhasePortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Position Start Value 2:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PositionStartValue2() As String
            Get
                Return ResourceManager.GetString("PositionStartValue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die must be a positive Number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PositiveNumber() As String
            Get
                Return ResourceManager.GetString("PositiveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Precision ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Precision() As String
            Get
                Return ResourceManager.GetString("Precision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Presentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Presentation() As String
            Get
                Return ResourceManager.GetString("Presentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Red() As String
            Get
                Return ResourceManager.GetString("Red", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reflexion Angle ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReflexionAngle() As String
            Get
                Return ResourceManager.GetString("ReflexionAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetIteration() As String
            Get
                Return ResourceManager.GetString("ResetIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sensitivity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Sensitivity() As String
            Get
                Return ResourceManager.GetString("Sensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Set the Startposition with the Mouse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SetStartPosition() As String
            Get
                Return ResourceManager.GetString("SetStartPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show first Splitpoints ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowSplitPoints() As String
            Get
                Return ResourceManager.GetString("ShowSplitPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Simulator() As String
            Get
                Return ResourceManager.GetString("Simulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Single Orbits ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SingleOrbits() As String
            Get
                Return ResourceManager.GetString("SingleOrbits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stadium ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Stadium() As String
            Get
                Return ResourceManager.GetString("Stadium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stadium Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StadiumBillard() As String
            Get
                Return ResourceManager.GetString("StadiumBillard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartIteration() As String
            Get
                Return ResourceManager.GetString("StartIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartParameter() As String
            Get
                Return ResourceManager.GetString("StartParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Startposition is not set for all Balls ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartPositionNotSet() As String
            Get
                Return ResourceManager.GetString("StartPositionNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die StartValue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue() As String
            Get
                Return ResourceManager.GetString("StartValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Value 1 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue1() As String
            Get
                Return ResourceManager.GetString("StartValue1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Value 2 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue2() As String
            Get
                Return ResourceManager.GetString("StartValue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Propose a Startvalue for this Protocol ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForProtocol() As String
            Get
                Return ResourceManager.GetString("StartvalueForProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Propose a Startvalue for this Targetvalue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForTargetvalue() As String
            Get
                Return ResourceManager.GetString("StartvalueForTargetvalue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Stetching Parameter has to be in the Interval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StretchingParameterInterval() As String
            Get
                Return ResourceManager.GetString("StretchingParameterInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Take over Start Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TakeOver() As String
            Get
                Return ResourceManager.GetString("TakeOver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target Protocol ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetProtocol() As String
            Get
                Return ResourceManager.GetString("TargetProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Targetvalue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetValue() As String
            Get
                Return ResourceManager.GetString("TargetValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tentmap ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tentmap() As String
            Get
                Return ResourceManager.GetString("Tentmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Test() As String
            Get
                Return ResourceManager.GetString("Test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Value  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TheValue() As String
            Get
                Return ResourceManager.GetString("TheValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Time Axis ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TimeAxis() As String
            Get
                Return ResourceManager.GetString("TimeAxis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Transitivity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Transitivity() As String
            Get
                Return ResourceManager.GetString("Transitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration in two Dimensions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TwoDimensions() As String
            Get
                Return ResourceManager.GetString("TwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unimodal Functions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UnimodalFunctions() As String
            Get
                Return ResourceManager.GetString("UnimodalFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Angle of upper Pendulum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UpperPendulumAngle() As String
            Get
                Return ResourceManager.GetString("UpperPendulumAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Value List 1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList1() As String
            Get
                Return ResourceManager.GetString("ValueList1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Value List 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList2() As String
            Get
                Return ResourceManager.GetString("ValueList2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This Valuerange is not allowed! It must be part of the interval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueRangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("ValueRangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Stretching of Time Axis ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property xStretching() As String
            Get
                Return ResourceManager.GetString("xStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Values ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property XValues() As String
            Get
                Return ResourceManager.GetString("XValues", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
