'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LabelsDE
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Simulator.LabelsDE", GetType(LabelsDE).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutSimulator() As String
            Get
                Return ResourceManager.GetString("AboutSimulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktion abgebrochen! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ActionStopped() As String
            Get
                Return ResourceManager.GetString("ActionStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alfa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Alfa() As String
            Get
                Return ResourceManager.GetString("Alfa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbe der nächsten Kugel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallColor() As String
            Get
                Return ResourceManager.GetString("BallColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kugelgeschwindigkeit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallSpeed() As String
            Get
                Return ResourceManager.GetString("BallSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Billard() As String
            Get
                Return ResourceManager.GetString("Billard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billardtisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BillardTable() As String
            Get
                Return ResourceManager.GetString("BillardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbiges Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ColoredDiagram() As String
            Get
                Return ResourceManager.GetString("ColoredDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startpunkt Koordinaten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoordinatesStartpoint() As String
            Get
                Return ResourceManager.GetString("CoordinatesStartpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Delta() As String
            Get
                Return ResourceManager.GetString("Delta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Differenzx2 - x1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Difference12() As String
            Get
                Return ResourceManager.GetString("Difference12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die d in [0,10] = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DinStretching() As String
            Get
                Return ResourceManager.GetString("DinStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zwischne Billardtisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawBillardTable() As String
            Get
                Return ResourceManager.GetString("DrawBillardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Funktionsgraph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawFunctionGraph() As String
            Get
                Return ResourceManager.GetString("DrawFunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dr. math. ETHZ Hermann Biner, Zermatt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrMathETH() As String
            Get
                Return ResourceManager.GetString("DrMathETH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elliptisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Elliptic() As String
            Get
                Return ResourceManager.GetString("Elliptic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Untersuchter Parameterbereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedParameterRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedParameterRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Untersuchter Wertebereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedValueRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedValueRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Experiment No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExperimentNo() As String
            Get
                Return ResourceManager.GetString("ExperimentNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Faktor C ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FactorC() As String
            Get
                Return ResourceManager.GetString("FactorC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feedback ist willkommen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Feedback() As String
            Get
                Return ResourceManager.GetString("Feedback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feigenbaum Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FeigenbaumDiagram() As String
            Get
                Return ResourceManager.GetString("FeigenbaumDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Funktionsgraph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FunctionGraph() As String
            Get
                Return ResourceManager.GetString("FunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Histogramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Histogram() As String
            Get
                Return ResourceManager.GetString("Histogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eine Dualzahl kann nur die Ziffern 0 und 1 enthalten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDualNumberDigits() As String
            Get
                Return ResourceManager.GetString("InvalidDualNumberDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Parameterwert oder Startwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidParameterOrIterationValue() As String
            Get
                Return ResourceManager.GetString("InvalidParameterOrIterationValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Protokoll kann nur die Zeichen 0 und 1 enthalten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidProtocolDigits() As String
            Get
                Return ResourceManager.GetString("InvalidProtocolDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiges Wertebereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserRanges() As String
            Get
                Return ResourceManager.GetString("InvalidUserRanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Iteration() As String
            Get
                Return ResourceManager.GetString("Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iterationstiefe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IterationDepth() As String
            Get
                Return ResourceManager.GetString("IterationDepth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die linke Intervallgrenze muss kleiner sein als die rechte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LeftSmallerRight() As String
            Get
                Return ResourceManager.GetString("LeftSmallerRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Log() As String
            Get
                Return ResourceManager.GetString("Log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logistisches Wachstum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogisticGrowth() As String
            Get
                Return ResourceManager.GetString("LogisticGrowth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerne per Mail an h.biner@bluewin.ch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MailTo() As String
            Get
                Return ResourceManager.GetString("MailTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Manual Simulator.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Manual() As String
            Get
                Return ResourceManager.GetString("Manual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dynamische Systeme.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MathDoc() As String
            Get
                Return ResourceManager.GetString("MathDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuBillard() As String
            Get
                Return ResourceManager.GetString("MnuBillard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;C-Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuCDiagram() As String
            Get
                Return ResourceManager.GetString("MnuCDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Schliessen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuClose() As String
            Get
                Return ResourceManager.GetString("MnuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Dokumentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuDocumentation() As String
            Get
                Return ResourceManager.GetString("MnuDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuEnglish() As String
            Get
                Return ResourceManager.GetString("MnuEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Feigenbaum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFeigenbaum() As String
            Get
                Return ResourceManager.GetString("MnuFeigenbaum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFile() As String
            Get
                Return ResourceManager.GetString("MnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Fraktale ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFractals() As String
            Get
                Return ResourceManager.GetString("MnuFractals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuGerman() As String
            Get
                Return ResourceManager.GetString("MnuGerman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Histogramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuHistogram() As String
            Get
                Return ResourceManager.GetString("MnuHistogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuInfo() As String
            Get
                Return ResourceManager.GetString("MnuInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuIteration() As String
            Get
                Return ResourceManager.GetString("MnuIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Julia Menge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuJuliaSet() As String
            Get
                Return ResourceManager.GetString("MnuJuliaSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Komplexe Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuKomplexIteration() As String
            Get
                Return ResourceManager.GetString("MnuKomplexIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuLanguage() As String
            Get
                Return ResourceManager.GetString("MnuLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hauptmenu ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMain() As String
            Get
                Return ResourceManager.GetString("MnuMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mandelbrot Menge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMandelbrotSet() As String
            Get
                Return ResourceManager.GetString("MnuMandelbrotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Handbuch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuManual() As String
            Get
                Return ResourceManager.GetString("MnuManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die M&amp;athematik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMathematics() As String
            Get
                Return ResourceManager.GetString("MnuMathematics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mechanik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMechanics() As String
            Get
                Return ResourceManager.GetString("MnuMechanics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Pendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuPendulum() As String
            Get
                Return ResourceManager.GetString("MnuPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Sensitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuSensitivity() As String
            Get
                Return ResourceManager.GetString("MnuSensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTest() As String
            Get
                Return ResourceManager.GetString("MnuTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Zweidimensional ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTwoDimensions() As String
            Get
                Return ResourceManager.GetString("MnuTwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Unimodale Funktionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuUnimodal() As String
            Get
                Return ResourceManager.GetString("MnuUnimodal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neue Kugel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NewBall() As String
            Get
                Return ResourceManager.GetString("NewBall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächste 100 Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next100Steps() As String
            Get
                Return ResourceManager.GetString("Next100Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächste 10 Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next10Steps() As String
            Get
                Return ResourceManager.GetString("Next10Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächstes Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextDiagram() As String
            Get
                Return ResourceManager.GetString("NextDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächster Schritt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextStep() As String
            Get
                Return ResourceManager.GetString("NextStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es gibt keine Kugeln auf dem Billardtisch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoBallsOnTable() As String
            Get
                Return ResourceManager.GetString("NoBallsOnTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Schnittpunkt gefunden! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoIntersectionPoint() As String
            Get
                Return ResourceManager.GetString("NoIntersectionPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wenn das Verhalten nicht chaotisch ist, wird das erwartete Resultat nicht auftreten. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NonChaoticBehaviour() As String
            Get
                Return ResourceManager.GetString("NonChaoticBehaviour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die nicht erlaubt. Er muss im Intervall sein: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotAlllowedValue() As String
            Get
                Return ResourceManager.GetString("NotAlllowedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diese Funktion ist momentan nicht implementiert! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotImplemented() As String
            Get
                Return ResourceManager.GetString("NotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfSteps() As String
            Get
                Return ResourceManager.GetString("NumberOfSteps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das muss ein numerischer Wert sein! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumericValue() As String
            Get
                Return ResourceManager.GetString("NumericValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die In diesem Projekt sind nur Zahlen vom Typ Integer oder Decimal erlaubt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OnlyDecAndInt() As String
            Get
                Return ResourceManager.GetString("OnlyDecAndInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Oval() As String
            Get
                Return ResourceManager.GetString("Oval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parabel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Parabola() As String
            Get
                Return ResourceManager.GetString("Parabola", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Parameter() As String
            Get
                Return ResourceManager.GetString("Parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieser PArameterbereich ist nicht erlaubt. Er muss Teil sein von: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParameterRangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("ParameterRangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phasenportrait t, alfa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PhasePortrait() As String
            Get
                Return ResourceManager.GetString("PhasePortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die muss eine positive Zahl sein! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PositiveNumber() As String
            Get
                Return ResourceManager.GetString("PositiveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Präzision ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Precision() As String
            Get
                Return ResourceManager.GetString("Precision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Präsentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Presentation() As String
            Get
                Return ResourceManager.GetString("Presentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Program Version 0.6 - 30.09.2023 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProgramVersion() As String
            Get
                Return ResourceManager.GetString("ProgramVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration zurücksetzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetIteration() As String
            Get
                Return ResourceManager.GetString("ResetIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sensitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Sensitivity() As String
            Get
                Return ResourceManager.GetString("Sensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze die Startposition mit der Maus! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SetStartPosition() As String
            Get
                Return ResourceManager.GetString("SetStartPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeige die ersten Splitpunkte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowSplitPoints() As String
            Get
                Return ResourceManager.GetString("ShowSplitPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Simulator() As String
            Get
                Return ResourceManager.GetString("Simulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einzelne Orbits ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SingleOrbits() As String
            Get
                Return ResourceManager.GetString("SingleOrbits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stadion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Stadium() As String
            Get
                Return ResourceManager.GetString("Stadium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartIteration() As String
            Get
                Return ResourceManager.GetString("StartIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartParameter() As String
            Get
                Return ResourceManager.GetString("StartParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Startposition ist nicht für alle Kugeln gesetzt! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartPositionNotSet() As String
            Get
                Return ResourceManager.GetString("StartPositionNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue() As String
            Get
                Return ResourceManager.GetString("StartValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert 1 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue1() As String
            Get
                Return ResourceManager.GetString("StartValue1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert 2 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue2() As String
            Get
                Return ResourceManager.GetString("StartValue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorschlag Startwert für dieses Protokoll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForProtocol() As String
            Get
                Return ResourceManager.GetString("StartvalueForProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorschlag Startwert für diesen Zielwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForTargetvalue() As String
            Get
                Return ResourceManager.GetString("StartvalueForTargetvalue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Dehnparameter muss im Intervall sein: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StretchingParameterInterval() As String
            Get
                Return ResourceManager.GetString("StretchingParameterInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Übernehme Startparameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TakeOver() As String
            Get
                Return ResourceManager.GetString("TakeOver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zielprotokoll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetProtocol() As String
            Get
                Return ResourceManager.GetString("TargetProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zielwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetValue() As String
            Get
                Return ResourceManager.GetString("TargetValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeltabbildung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tentmap() As String
            Get
                Return ResourceManager.GetString("Tentmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Test() As String
            Get
                Return ResourceManager.GetString("Test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Wert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TheValue() As String
            Get
                Return ResourceManager.GetString("TheValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeitachse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TimeAxis() As String
            Get
                Return ResourceManager.GetString("TimeAxis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Transitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Transitivity() As String
            Get
                Return ResourceManager.GetString("Transitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration in zwei Dimensionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TwoDimensions() As String
            Get
                Return ResourceManager.GetString("TwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unimodale Funktionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UnimodalFunctions() As String
            Get
                Return ResourceManager.GetString("UnimodalFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wertliste 1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList1() As String
            Get
                Return ResourceManager.GetString("ValueList1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wertliste 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList2() As String
            Get
                Return ResourceManager.GetString("ValueList2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Dehnung der Zeitachse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property xStretching() As String
            Get
                Return ResourceManager.GetString("xStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Werte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property XValues() As String
            Get
                Return ResourceManager.GetString("XValues", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
