'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LabelsDE
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Simulator.LabelsDE", GetType(LabelsDE).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fortsetzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _Continue() As String
            Get
                Return ResourceManager.GetString("Continue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _Stop() As String
            Get
                Return ResourceManager.GetString("Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutSimulator() As String
            Get
                Return ResourceManager.GetString("AboutSimulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktion abgebrochen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ActionStopped() As String
            Get
                Return ResourceManager.GetString("ActionStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alfa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Alfa() As String
            Get
                Return ResourceManager.GetString("Alfa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbe der nächsten Kugel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallColor() As String
            Get
                Return ResourceManager.GetString("BallColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kugelgeschwindigkeit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BallSpeed() As String
            Get
                Return ResourceManager.GetString("BallSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Billiard() As String
            Get
                Return ResourceManager.GetString("Billiard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billardtisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BilliardTable() As String
            Get
                Return ResourceManager.GetString("BilliardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schwarz ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Black() As String
            Get
                Return ResourceManager.GetString("Black", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Blue() As String
            Get
                Return ResourceManager.GetString("Blue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die C-Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property C_Diagram() As String
            Get
                Return ResourceManager.GetString("C-Diagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein Klassenname muss mit derm Prefic &apos;Cls&apos; starten und eine Länge &gt; 3 haben! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClassNameViolation() As String
            Get
                Return ResourceManager.GetString("ClassNameViolation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Euler Implizit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsBackwardEuler() As String
            Get
                Return ResourceManager.GetString("ClsBackwardEuler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schwingendes Federpendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsCombinedPendulum() As String
            Get
                Return ResourceManager.GetString("ClsCombinedPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Doppelpendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsDoublePendulum() As String
            Get
                Return ResourceManager.GetString("ClsDoublePendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elliptisches Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsEllipseBilliardball() As String
            Get
                Return ResourceManager.GetString("ClsEllipseBilliardball", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Euler Explizit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsForwardEuler() As String
            Get
                Return ResourceManager.GetString("ClsForwardEuler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logistisches Wachstum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsLogisticGrowth() As String
            Get
                Return ResourceManager.GetString("ClsLogisticGrowth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Implizite Mittelpunktsregel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsMidpointImplicit() As String
            Get
                Return ResourceManager.GetString("ClsMidpointImplicit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ovales Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsOvalBilliardball() As String
            Get
                Return ResourceManager.GetString("ClsOvalBilliardball", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parabel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsParabola() As String
            Get
                Return ResourceManager.GetString("ClsParabola", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reales Federpendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsRealSpringPendulum() As String
            Get
                Return ResourceManager.GetString("ClsRealSpringPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Runge Kutta 4 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsRungeKutta4() As String
            Get
                Return ResourceManager.GetString("ClsRungeKutta4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rüttelpendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsShakedPendulum() As String
            Get
                Return ResourceManager.GetString("ClsShakedPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Billard im Stadion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsStadiumBilliardball() As String
            Get
                Return ResourceManager.GetString("ClsStadiumBilliardball", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeltabbildung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsTentmap() As String
            Get
                Return ResourceManager.GetString("ClsTentmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die f(z)=z^3-1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClsUnitRoots3() As String
            Get
                Return ResourceManager.GetString("ClsUnitRoots3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbiges Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ColoredDiagram() As String
            Get
                Return ResourceManager.GetString("ColoredDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtenergie ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CombinedPendulumC() As String
            Get
                Return ResourceManager.GetString("CombinedPendulumC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startpunkt Koordinaten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoordinatesStartpoint() As String
            Get
                Return ResourceManager.GetString("CoordinatesStartpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zylinder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Cylinder() As String
            Get
                Return ResourceManager.GetString("Cylinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Delta() As String
            Get
                Return ResourceManager.GetString("Delta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Differenz ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Difference() As String
            Get
                Return ResourceManager.GetString("Difference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Differenz x2 - x1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Difference12() As String
            Get
                Return ResourceManager.GetString("Difference12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die d in [0,10] = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DinStretching() As String
            Get
                Return ResourceManager.GetString("DinStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Dokument konnte nicht gefunden werden:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocumentNotFound() As String
            Get
                Return ResourceManager.GetString("DocumentNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtenergie ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DoublePendulumC() As String
            Get
                Return ResourceManager.GetString("DoublePendulumC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Billardtisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawBilliardTable() As String
            Get
                Return ResourceManager.GetString("DrawBilliardTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Funktionsgraph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrawFunctionGraph() As String
            Get
                Return ResourceManager.GetString("DrawFunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dr. math. ETHZ Hermann Biner, Zermatt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DrMathETH() As String
            Get
                Return ResourceManager.GetString("DrMathETH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elliptisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Elliptic() As String
            Get
                Return ResourceManager.GetString("Elliptic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtenergie ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Energy() As String
            Get
                Return ResourceManager.GetString("Energy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Untersuchter Parameterbereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedParameterRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedParameterRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Untersuchter Werteparameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedValueParameter() As String
            Get
                Return ResourceManager.GetString("ExaminatedValueParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Untersuchter Wertebereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExaminatedValueRange() As String
            Get
                Return ResourceManager.GetString("ExaminatedValueRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Experiment No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExperimentNo() As String
            Get
                Return ResourceManager.GetString("ExperimentNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Faktor C ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FactorC() As String
            Get
                Return ResourceManager.GetString("FactorC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feedback ist willkommen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Feedback() As String
            Get
                Return ResourceManager.GetString("Feedback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feigenbaum Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FeigenbaumDiagram() As String
            Get
                Return ResourceManager.GetString("FeigenbaumDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fülle Phasenportrait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FillPhasePortrait() As String
            Get
                Return ResourceManager.GetString("FillPhasePortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Funktionsgraph ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FunctionGraph() As String
            Get
                Return ResourceManager.GetString("FunctionGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grün ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Green() As String
            Get
                Return ResourceManager.GetString("Green", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Histogramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Histogram() As String
            Get
                Return ResourceManager.GetString("Histogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stosspunkt Parameter t ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HitPoint() As String
            Get
                Return ResourceManager.GetString("HitPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unabhängige Pendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Independent() As String
            Get
                Return ResourceManager.GetString("Independent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eine Dualzahl kann nur die Ziffern 0 und 1 enthalten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDualNumberDigits() As String
            Get
                Return ResourceManager.GetString("InvalidDualNumberDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Parameterwert oder Startwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidParameterOrIterationValue() As String
            Get
                Return ResourceManager.GetString("InvalidParameterOrIterationValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einige PArameterwerte sind ungültig ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidParameters() As String
            Get
                Return ResourceManager.GetString("InvalidParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Protokoll kann nur die Zeichen 0 und 1 enthalten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidProtocolDigits() As String
            Get
                Return ResourceManager.GetString("InvalidProtocolDigits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Wertebereich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserRanges() As String
            Get
                Return ResourceManager.GetString("InvalidUserRanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Iteration() As String
            Get
                Return ResourceManager.GetString("Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iterationstiefe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IterationDepth() As String
            Get
                Return ResourceManager.GetString("IterationDepth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die linke Intervallgrenze muss kleiner sein als die rechte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LeftSmallerRight() As String
            Get
                Return ResourceManager.GetString("LeftSmallerRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Log() As String
            Get
                Return ResourceManager.GetString("Log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Winkel des unteren Pendels ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LowerPendulumAngle() As String
            Get
                Return ResourceManager.GetString("LowerPendulumAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Magenta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Magenta() As String
            Get
                Return ResourceManager.GetString("Magenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerne per Mail an h.biner@bluewin.ch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MailTo() As String
            Get
                Return ResourceManager.GetString("MailTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Handbuch.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Manual() As String
            Get
                Return ResourceManager.GetString("Manual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Massenverhältnis M ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MassRatioM() As String
            Get
                Return ResourceManager.GetString("MassRatioM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dynamische Systeme.pdf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MathDoc() As String
            Get
                Return ResourceManager.GetString("MathDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine implementierende Klasse gefunden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MissingImplementation() As String
            Get
                Return ResourceManager.GetString("MissingImplementation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Billard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuBilliard() As String
            Get
                Return ResourceManager.GetString("MnuBilliard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;C-DiagrammBillard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuCDiagramBilliard() As String
            Get
                Return ResourceManager.GetString("MnuCDiagramBilliard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Schliessen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuClose() As String
            Get
                Return ResourceManager.GetString("MnuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Dokumentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuDocumentation() As String
            Get
                Return ResourceManager.GetString("MnuDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuEnglish() As String
            Get
                Return ResourceManager.GetString("MnuEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Feigenbaum ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFeigenbaum() As String
            Get
                Return ResourceManager.GetString("MnuFeigenbaum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Datei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFile() As String
            Get
                Return ResourceManager.GetString("MnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Fraktale ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuFractals() As String
            Get
                Return ResourceManager.GetString("MnuFractals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuGerman() As String
            Get
                Return ResourceManager.GetString("MnuGerman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Histogramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuHistogram() As String
            Get
                Return ResourceManager.GetString("MnuHistogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuInfo() As String
            Get
                Return ResourceManager.GetString("MnuInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuIteration() As String
            Get
                Return ResourceManager.GetString("MnuIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Komplexe Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuKomplexIteration() As String
            Get
                Return ResourceManager.GetString("MnuKomplexIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuLanguage() As String
            Get
                Return ResourceManager.GetString("MnuLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hauptmenu ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMain() As String
            Get
                Return ResourceManager.GetString("MnuMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mandelbrot Menge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMandelbrot() As String
            Get
                Return ResourceManager.GetString("MnuMandelbrot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Handbuch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuManual() As String
            Get
                Return ResourceManager.GetString("MnuManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die M&amp;athematik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMathematics() As String
            Get
                Return ResourceManager.GetString("MnuMathematics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Mechanik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuMechanics() As String
            Get
                Return ResourceManager.GetString("MnuMechanics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Newton Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuNewton() As String
            Get
                Return ResourceManager.GetString("MnuNewton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Pendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuPendulum() As String
            Get
                Return ResourceManager.GetString("MnuPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Sensitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuSensitivity() As String
            Get
                Return ResourceManager.GetString("MnuSensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTest() As String
            Get
                Return ResourceManager.GetString("MnuTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Zweidimensional ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuTwoDimensions() As String
            Get
                Return ResourceManager.GetString("MnuTwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;Wachstumsmodelle ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MnuUnimodal() As String
            Get
                Return ResourceManager.GetString("MnuUnimodal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neue Kugel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NewBall() As String
            Get
                Return ResourceManager.GetString("NewBall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Newton Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NewtonIteration() As String
            Get
                Return ResourceManager.GetString("NewtonIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächste 100 Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next100Steps() As String
            Get
                Return ResourceManager.GetString("Next100Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächste 10 Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Next10Steps() As String
            Get
                Return ResourceManager.GetString("Next10Steps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächstes Diagramm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextDiagram() As String
            Get
                Return ResourceManager.GetString("NextDiagram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nächster Schritt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NextStep() As String
            Get
                Return ResourceManager.GetString("NextStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es gibt keine Kugeln auf dem Billardtisch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoBallsOnTable() As String
            Get
                Return ResourceManager.GetString("NoBallsOnTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Schnittpunkt gefunden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoIntersectionPoint() As String
            Get
                Return ResourceManager.GetString("NoIntersectionPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wenn das Verhalten nicht chaotisch ist, wird das erwartete Resultat nicht auftreten. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NonChaoticBehaviour() As String
            Get
                Return ResourceManager.GetString("NonChaoticBehaviour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Startpunkt gesetzt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoStartPointSet() As String
            Get
                Return ResourceManager.GetString("NoStartPointSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  ist nicht erlaubt. Er muss im Intervall sein:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotAlllowedValue() As String
            Get
                Return ResourceManager.GetString("NotAlllowedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diese Funktion ist momentan nicht implementiert! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotImplemented() As String
            Get
                Return ResourceManager.GetString("NotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl Schritte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfSteps() As String
            Get
                Return ResourceManager.GetString("NumberOfSteps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Numerisches Verfahren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumericMethod() As String
            Get
                Return ResourceManager.GetString("NumericMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Numerische Methoden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumericMethods() As String
            Get
                Return ResourceManager.GetString("NumericMethods", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das muss ein numerischer Wert sein! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NumericValue() As String
            Get
                Return ResourceManager.GetString("NumericValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die In diesem Projekt sind nur Zahlen vom Typ Integer oder Decimal erlaubt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OnlyDecAndInt() As String
            Get
                Return ResourceManager.GetString("OnlyDecAndInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oval ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Oval() As String
            Get
                Return ResourceManager.GetString("Oval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Parameter() As String
            Get
                Return ResourceManager.GetString("Parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Parameterliste: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParameterList() As String
            Get
                Return ResourceManager.GetString("ParameterList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieser Parameterbereich ist nicht erlaubt. Er muss Teil sein von: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParameterRangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("ParameterRangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Pendulum() As String
            Get
                Return ResourceManager.GetString("Pendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phasenportrait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PhasePortrait() As String
            Get
                Return ResourceManager.GetString("PhasePortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Poincaré Schnitt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PoincareSection() As String
            Get
                Return ResourceManager.GetString("PoincareSection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Position Startwert 2:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PositionStartValue2() As String
            Get
                Return ResourceManager.GetString("PositionStartValue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die muss eine positive Zahl sein! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PositiveNumber() As String
            Get
                Return ResourceManager.GetString("PositiveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Präzision ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Precision() As String
            Get
                Return ResourceManager.GetString("Precision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Präsentation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Presentation() As String
            Get
                Return ResourceManager.GetString("Presentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Prokotoll p,q,x,y ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Protocol() As String
            Get
                Return ResourceManager.GetString("Protocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rot ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Red() As String
            Get
                Return ResourceManager.GetString("Red", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reflexionswinkel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReflexionAngle() As String
            Get
                Return ResourceManager.GetString("ReflexionAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Reset() As String
            Get
                Return ResourceManager.GetString("Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration zurücksetzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetIteration() As String
            Get
                Return ResourceManager.GetString("ResetIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sensitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Sensitivity() As String
            Get
                Return ResourceManager.GetString("Sensitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze die Startposition mit der Maus ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SetStartPosition() As String
            Get
                Return ResourceManager.GetString("SetStartPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gesamtenergie ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShakedPendulumC() As String
            Get
                Return ResourceManager.GetString("ShakedPendulumC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rüttelfrequenz ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShakingFrequency() As String
            Get
                Return ResourceManager.GetString("ShakingFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orbit anzeigen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowOrbit() As String
            Get
                Return ResourceManager.GetString("ShowOrbit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeige die ersten Splitpunkte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowSplitPoints() As String
            Get
                Return ResourceManager.GetString("ShowSplitPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Simulator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Simulator() As String
            Get
                Return ResourceManager.GetString("Simulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einzelne Orbits ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SingleOrbits() As String
            Get
                Return ResourceManager.GetString("SingleOrbits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Federkonstante ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SpringConstant() As String
            Get
                Return ResourceManager.GetString("SpringConstant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Federpendel und numerische Methoden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SpringPendulum() As String
            Get
                Return ResourceManager.GetString("SpringPendulum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Frequenz Federpendel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SpringPendulumFrequency() As String
            Get
                Return ResourceManager.GetString("SpringPendulumFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stadion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Stadium() As String
            Get
                Return ResourceManager.GetString("Stadium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Start() As String
            Get
                Return ResourceManager.GetString("Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Iteration ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartIteration() As String
            Get
                Return ResourceManager.GetString("StartIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartParameter() As String
            Get
                Return ResourceManager.GetString("StartParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Startposition ist nicht für alle Kugeln gesetzt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartPositionNotSet() As String
            Get
                Return ResourceManager.GetString("StartPositionNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue() As String
            Get
                Return ResourceManager.GetString("StartValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert 1 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue1() As String
            Get
                Return ResourceManager.GetString("StartValue1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startwert 2 = ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartValue2() As String
            Get
                Return ResourceManager.GetString("StartValue2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorschlag Startwert für dieses Protokoll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForProtocol() As String
            Get
                Return ResourceManager.GetString("StartvalueForProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorschlag Startwert für diesen Zielwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartvalueForTargetvalue() As String
            Get
                Return ResourceManager.GetString("StartvalueForTargetvalue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schrittweite ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StepWidth() As String
            Get
                Return ResourceManager.GetString("StepWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gestreckte Anzeige ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StretchedMode() As String
            Get
                Return ResourceManager.GetString("StretchedMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Dehnparameter muss im Intervall sein: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StretchingParameterInterval() As String
            Get
                Return ResourceManager.GetString("StretchingParameterInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Übernehme Startparameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TakeOver() As String
            Get
                Return ResourceManager.GetString("TakeOver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zielprotokoll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetProtocol() As String
            Get
                Return ResourceManager.GetString("TargetProtocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zielwert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TargetValue() As String
            Get
                Return ResourceManager.GetString("TargetValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Test() As String
            Get
                Return ResourceManager.GetString("Test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test Modus ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TestMode() As String
            Get
                Return ResourceManager.GetString("TestMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Wert  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TheValue() As String
            Get
                Return ResourceManager.GetString("TheValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeitachse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TimeAxis() As String
            Get
                Return ResourceManager.GetString("TimeAxis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Torus ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Torus() As String
            Get
                Return ResourceManager.GetString("Torus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Transitivität ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Transitivity() As String
            Get
                Return ResourceManager.GetString("Transitivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iteration in zwei Dimensionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TwoDimensions() As String
            Get
                Return ResourceManager.GetString("TwoDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type Phasenportrait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TypeofPhaseportrait() As String
            Get
                Return ResourceManager.GetString("TypeofPhaseportrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unimodale Funktionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UnimodalFunctions() As String
            Get
                Return ResourceManager.GetString("UnimodalFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Winkel des oberen Pendels ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UpperPendulumAngle() As String
            Get
                Return ResourceManager.GetString("UpperPendulumAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wertliste 1 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList1() As String
            Get
                Return ResourceManager.GetString("ValueList1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wertliste 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueList2() As String
            Get
                Return ResourceManager.GetString("ValueList2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieser Wertebereich ist nicht erlaubt. Er muss Teil sein von: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValueRangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("ValueRangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieser X-Bereich ist nicht erlaubt. Er muss Teil sein von: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property X_RangeNotAllowed() As String
            Get
                Return ResourceManager.GetString("X-RangeNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Dehnung der Zeitachse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property xStretching() As String
            Get
                Return ResourceManager.GetString("xStretching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die x-Werte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property XValues() As String
            Get
                Return ResourceManager.GetString("XValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieser Y-Bereich ist nicht erlaubt. Er muss Teil sein von: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Y_RangeNotAllowed1() As String
            Get
                Return ResourceManager.GetString("Y-RangeNotAllowed1", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
